install:
 - mvn -Pwildfly2201 clean
script:
 - mvn --settings settings.xml -B -Pwildfly2201 integration-test

language: java
jdk:
  - oraclejdk8
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
