package org.jboss.wise.test.integration.complex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3-SNAPSHOT (1439267)
 * 2013-02-20T16:44:23.123+01:00
 * Generated source version: 2.7.3-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", name = "Registration")
@XmlSeeAlso({ObjectFactory.class})
public interface Registration {

    @WebResult(name = "RegisteredID", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.Register")
    @WebMethod(operationName = "Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.RegisterResponse")
    public long register(
        @WebParam(name = "Customer", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        org.jboss.wise.test.integration.complex.Customer customer,
        @WebParam(name = "When", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        java.lang.Object when
    ) throws ValidationFault_Exception, AlreadyRegisteredFault_Exception;

    @WebResult(name = "Statistics", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
    @RequestWrapper(localName = "GetStatistics", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.GetStatistics")
    @WebMethod(operationName = "GetStatistics")
    @ResponseWrapper(localName = "GetStatisticsResponse", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.GetStatisticsResponse")
    public org.jboss.wise.test.integration.complex.Statistics getStatistics(
        @WebParam(name = "Customer", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        org.jboss.wise.test.integration.complex.Customer customer
    );

    @RequestWrapper(localName = "Echo", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.Echo")
    @WebMethod(operationName = "Echo")
    @ResponseWrapper(localName = "EchoResponse", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.EchoResponse")
    public void echo(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Customer", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        javax.xml.ws.Holder<Customer> customer
    );

    @WebResult(name = "done", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
    @RequestWrapper(localName = "RegisterForInvoice", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.RegisterForInvoice")
    @WebMethod(operationName = "RegisterForInvoice")
    @ResponseWrapper(localName = "RegisterForInvoiceResponse", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.RegisterForInvoiceResponse")
    public boolean registerForInvoice(
        @WebParam(name = "InvoiceCustomer", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        org.jboss.wise.test.integration.complex.InvoiceCustomer invoiceCustomer
    ) throws ValidationFault_Exception, AlreadyRegisteredFault_Exception;

    @WebResult(name = "RegisteredIDs", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
    @RequestWrapper(localName = "BulkRegister", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.BulkRegister")
    @WebMethod(operationName = "BulkRegister")
    @ResponseWrapper(localName = "BulkRegisterResponse", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/", className = "org.jboss.wise.test.integration.complex.BulkRegisterResponse")
    public java.util.List<java.lang.Long> bulkRegister(
        @WebParam(name = "Customers", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        java.util.List<org.jboss.wise.test.integration.complex.Customer> customers,
        @WebParam(name = "When", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
        java.lang.Object when
    ) throws ValidationFault_Exception, AlreadyRegisteredFault_Exception;
}
